export type RegionType = {
    id: string
    value: string
    label: string
}

export type DistrictType = {
    id: string
    region_id: string
    value: string
    label: string
}

export const REGIONS: RegionType[] = [
    {
        id: "1",
        value: "Qoraqalpog‘iston Respublikasi",
        label: "Qoraqalpog‘iston Respublikasi",
    },
    { id: "2", value: "Andijon viloyati", label: "Andijon viloyati" },
    { id: "3", value: "Buxoro viloyati", label: "Buxoro viloyati" },
    { id: "4", value: "Jizzax viloyati", label: "Jizzax viloyati" },
    { id: "5", value: "Qashqadaryo viloyati", label: "Qashqadaryo viloyati" },
    { id: "6", value: "Navoiy viloyati", label: "Navoiy viloyati" },
    { id: "7", value: "Namangan viloyati", label: "Namangan viloyati" },
    { id: "8", value: "Samarqand viloyati", label: "Samarqand viloyati" },
    { id: "9", value: "Surxandaryo viloyati", label: "Surxandaryo viloyati" },
    { id: "10", value: "Sirdaryo viloyati", label: "Sirdaryo viloyati" },
    { id: "11", value: "Toshkent viloyati", label: "Toshkent viloyati" },
    { id: "12", value: "Farg‘ona viloyati", label: "Farg‘ona viloyati" },
    { id: "13", value: "Xorazm viloyati", label: "Xorazm viloyati" },
    { id: "14", value: "Toshkent shahar", label: "Toshkent shahar" },
]

export const DISTRICTS: DistrictType[] = [
    { id: "15", region_id: "1", value: "Amudaryo tumani", label: "Amudaryo tumani" },
    { id: "16", region_id: "1", value: "Beruniy tumani", label: "Beruniy tumani" },
    { id: "17", region_id: "1", value: "Kegayli tumani", label: "Kegayli tumani" },
    {
        id: "18",
        region_id: "1",
        value: "Qonlikol tumani",
        label: "Qonlikol tumani",
    },
    { id: "19", region_id: "1", value: "Qoraozak tumani", label: "Qoraozak tumani" },
    {
        id: "20",
        region_id: "1",
        value: "Qongirot tumani",
        label: "Qongirot tumani",
    },
    { id: "21", region_id: "1", value: "Moynoq tumani", label: "Moynoq tumani" },
    { id: "22", region_id: "1", value: "Nukus tumani", label: "Nukus tumani" },
    { id: "23", region_id: "1", value: "Nukus shahri", label: "Nukus shahri" },
    {
        id: "24",
        region_id: "1",
        value: "Taxtakopir tumani",
        label: "Taxtakopir tumani",
    },
    { id: "25", region_id: "1", value: "Tortkol tumani", label: "Tortkol tumani" },
    { id: "26", region_id: "1", value: "Xojayli tumani", label: "Xojayli tumani" },
    { id: "27", region_id: "1", value: "Chimboy tumani", label: "Chimboy tumani" },
    { id: "28", region_id: "1", value: "Shumanay tumani", label: "Shumanay tumani" },
    {
        id: "29",
        region_id: "1",
        value: "Ellikqala tumani",
        label: "Ellikqala tumani",
    },
    { id: "30", region_id: "2", value: "Andijon shahri", label: "Andijon shahri" },
    { id: "31", region_id: "2", value: "Andijon tumani", label: "Andijon tumani" },
    { id: "32", region_id: "2", value: "Asaka tumani", label: "Asaka tumani" },
    { id: "33", region_id: "2", value: "Baliqchi tumani", label: "Baliqchi tumani" },
    {
        id: "34",
        region_id: "2",
        value: "Buloqboshi tumani",
        label: "Buloqboshi tumani",
    },
    { id: "35", region_id: "2", value: "Boz tumani", label: "Boz tumani" },
    {
        id: "36",
        region_id: "2",
        value: "Jalaquduq tumani",
        label: "Jalaquduq tumani",
    },
    { id: "37", region_id: "2", value: "Izbosgan tumani", label: "Izbosgan tumani" },
    { id: "38", region_id: "2", value: "Qorasuv shahri", label: "Qorasuv shahri" },
    {
        id: "39",
        region_id: "2",
        value: "Qorgontepa tumani",
        label: "Qorgontepa tumani",
    },
    { id: "40", region_id: "2", value: "Marhamat tumani", label: "Marhamat tumani" },
    {
        id: "41",
        region_id: "2",
        value: "Oltinkol tumani",
        label: "Oltinkol tumani",
    },
    {
        id: "42",
        region_id: "2",
        value: "Paxtaobod tumani",
        label: "Paxtaobod tumani",
    },
    { id: "43", region_id: "2", value: "Ulugnor tumani", label: "Ulugnor tumani" },
    { id: "44", region_id: "2", value: "Xonabod tumani", label: "Xonabod tumani" },
    {
        id: "45",
        region_id: "2",
        value: "Xojaobod tumani",
        label: "Xojaobod tumani",
    },
    {
        id: "46",
        region_id: "2",
        value: "Shahrixon tumani",
        label: "Shahrixon tumani",
    },
    { id: "47", region_id: "3", value: "Buxoro shahri", label: "Buxoro shahri" },
    { id: "48", region_id: "3", value: "Buxoro tumani", label: "Buxoro tumani" },
    { id: "49", region_id: "3", value: "Vobkent tumani", label: "Vobkent tumani" },
    {
        id: "50",
        region_id: "3",
        value: "Gijduvon tumani",
        label: "Gijduvon tumani",
    },
    { id: "51", region_id: "3", value: "Jondor tumani", label: "Jondor tumani" },
    { id: "52", region_id: "3", value: "Kogon tumani", label: "Kogon tumani" },
    { id: "53", region_id: "3", value: "Kogon shahri", label: "Kogon shahri" },
    { id: "54", region_id: "3", value: "Qorakol tumani", label: "Qorakol tumani" },
    {
        id: "55",
        region_id: "3",
        value: "Qorovulbozor tumani",
        label: "Qorovulbozor tumani",
    },
    { id: "56", region_id: "3", value: "Olot tumani", label: "Olot tumani" },
    { id: "57", region_id: "3", value: "Peshku tumani", label: "Peshku tumani" },
    { id: "58", region_id: "3", value: "Romitan tumani", label: "Romitan tumani" },
    {
        id: "59",
        region_id: "3",
        value: "Shofirkon tumani",
        label: "Shofirkon tumani",
    },
    { id: "60", region_id: "4", value: "Arnasoy tumani", label: "Arnasoy tumani" },
    { id: "61", region_id: "4", value: "Baxmal tumani", label: "Baxmal tumani" },
    {
        id: "62",
        region_id: "4",
        value: "Gallaorol tumani",
        label: "Gallaorol tumani",
    },
    { id: "63", region_id: "4", value: "Dostlik tumani", label: "Dostlik tumani" },
    {
        id: "64",
        region_id: "4",
        value: "Sh.Rashidov tumani",
        label: "Sh.Rashidov tumani",
    },
    { id: "65", region_id: "4", value: "Jizzax shahri", label: "Jizzax shahri" },
    { id: "66", region_id: "4", value: "Zarbdor tumani", label: "Zarbdor tumani" },
    {
        id: "67",
        region_id: "4",
        value: "Zafarobod tumani",
        label: "Zafarobod tumani",
    },
    { id: "68", region_id: "4", value: "Zomin tumani", label: "Zomin tumani" },
    {
        id: "69",
        region_id: "4",
        value: "Mirzachol tumani",
        label: "Mirzachol tumani",
    },
    { id: "70", region_id: "4", value: "Paxtakor tumani", label: "Paxtakor tumani" },
    { id: "71", region_id: "4", value: "Forish tumani", label: "Forish tumani" },
    {
        id: "72",
        region_id: "4",
        value: "Yangiobod tumani",
        label: "Yangiobod tumani",
    },
    { id: "73", region_id: "5", value: "Guzor tumani", label: "Guzor tumani" },
    {
        id: "74",
        region_id: "5",
        value: "Dehqonobod tumani",
        label: "Dehqonobod tumani",
    },
    { id: "75", region_id: "5", value: "Qamashi tumani", label: "Qamashi tumani" },
    { id: "76", region_id: "5", value: "Qarshi tumani", label: "Qarshi tumani" },
    { id: "77", region_id: "5", value: "Qarshi shahri", label: "Qarshi shahri" },
    { id: "78", region_id: "5", value: "Kasbi tumani", label: "Kasbi tumani" },
    { id: "79", region_id: "5", value: "Kitob tumani", label: "Kitob tumani" },
    { id: "80", region_id: "5", value: "Koson tumani", label: "Koson tumani" },
    {
        id: "81",
        region_id: "5",
        value: "Mirishkor tumani",
        label: "Mirishkor tumani",
    },
    { id: "82", region_id: "5", value: "Muborak tumani", label: "Muborak tumani" },
    { id: "83", region_id: "5", value: "Nishon tumani", label: "Nishon tumani" },
    { id: "84", region_id: "5", value: "Chiroqchi tumani", label: "Chiroqchi tumani" },
    {
        id: "85",
        region_id: "5",
        value: "Shahrisabz tumani",
        label: "Shahrisabz tumani",
    },
    { id: "86", region_id: "5", value: "Yakkabog tumani", label: "Yakkabog tumani" },
    { id: "87", region_id: "6", value: "Zarafshon shahri", label: "Zarafshon shahri" },
    { id: "88", region_id: "6", value: "Karmana tumani", label: "Karmana tumani" },
    {
        id: "89",
        region_id: "6",
        value: "Qiziltepa tumani",
        label: "Qiziltepa tumani",
    },
    { id: "90", region_id: "6", value: "Konimex tumani", label: "Konimex tumani" },
    { id: "91", region_id: "6", value: "Navbahor tumani", label: "Navbahor tumani" },
    { id: "92", region_id: "6", value: "Navoiy shahri", label: "Navoiy shahri" },
    { id: "93", region_id: "6", value: "Nurota tumani", label: "Nurota tumani" },
    { id: "94", region_id: "6", value: "Tomdi tumani", label: "Tomdi tumani" },
    { id: "95", region_id: "6", value: "Uchquduq tumani", label: "Uchquduq tumani" },
    { id: "96", region_id: "6", value: "Xatirchi tumani", label: "Xatirchi tumani" },
    { id: "97", region_id: "7", value: "Kosonsoy tumani", label: "Kosonsoy tumani" },
    {
        id: "98",
        region_id: "7",
        value: "Mingbuloq tumani",
        label: "Mingbuloq tumani",
    },
    { id: "99", region_id: "7", value: "Namangan tumani", label: "Namangan tumani" },
    { id: "100", region_id: "7", value: "Namangan shahri", label: "Namangan shahri" },
    { id: "101", region_id: "7", value: "Norin tumani", label: "Norin tumani" },
    { id: "102", region_id: "7", value: "Pop tumani", label: "Pop tumani" },
    {
        id: "103",
        region_id: "7",
        value: "Toraqorgon tumani",
        label: "Toraqorgon tumani",
    },
    { id: "104", region_id: "7", value: "Uychi tumani", label: "Uychi tumani" },
    {
        id: "105",
        region_id: "7",
        value: "Uchqorgon tumani",
        label: "Uchqorgon tumani",
    },
    { id: "106", region_id: "7", value: "Chortoq tumani", label: "Chortoq tumani" },
    { id: "107", region_id: "7", value: "Chust tumani", label: "Chust tumani" },
    {
        id: "108",
        region_id: "7",
        value: "Yangiqorgon tumani",
        label: "Yangiqorgon tumani",
    },
    {
        id: "109",
        region_id: "8",
        value: "Bulungur tumani",
        label: "Bulungur tumani",
    },
    { id: "110", region_id: "8", value: "Jomboy tumani", label: "Jomboy tumani" },
    { id: "111", region_id: "8", value: "Ishtixon tumani", label: "Ishtixon tumani" },
    {
        id: "112",
        region_id: "8",
        value: "Kattaqorgon tumani",
        label: "Kattaqorgon tumani",
    },
    {
        id: "113",
        region_id: "8",
        value: "Kattaqorgon shahri",
        label: "Kattaqorgon shahri",
    },
    {
        id: "114",
        region_id: "8",
        value: "Qoshrabot tumani",
        label: "Qoshrabot tumani",
    },
    { id: "115", region_id: "8", value: "Narpay tumani", label: "Narpay tumani" },
    { id: "116", region_id: "8", value: "Nurabod tumani", label: "Nurabod tumani" },
    { id: "117", region_id: "8", value: "Oqdaryo tumani", label: "Oqdaryo tumani" },
    { id: "118", region_id: "8", value: "Payariq tumani", label: "Payariq tumani" },
    {
        id: "119",
        region_id: "8",
        value: "Pastargom tumani",
        label: "Pastargom tumani",
    },
    { id: "120", region_id: "8", value: "Paxtachi tumani", label: "Paxtachi tumani" },
    {
        id: "121",
        region_id: "8",
        value: "Samarqand tumani",
        label: "Samarqand tumani",
    },
    { id: "122", region_id: "8", value: "Samarqand shahri", label: "Samarqand shahri" },
    { id: "123", region_id: "8", value: "Toyloq tumani", label: "Toyloq tumani" },
    { id: "124", region_id: "8", value: "Urgut tumani", label: "Urgut tumani" },
    { id: "125", region_id: "9", value: "Angor tumani", label: "Angor tumani" },
    { id: "126", region_id: "9", value: "Boysun tumani", label: "Boysun tumani" },
    { id: "127", region_id: "9", value: "Denov tumani", label: "Denov tumani" },
    {
        id: "128",
        region_id: "9",
        value: "Jarqorgon tumani",
        label: "Jarqorgon tumani",
    },
    { id: "129", region_id: "9", value: "Qiziriq tumani", label: "Qiziriq tumani" },
    {
        id: "130",
        region_id: "9",
        value: "Qomqorgon tumani",
        label: "Qomqorgon tumani",
    },
    {
        id: "131",
        region_id: "9",
        value: "Muzrabot tumani",
        label: "Muzrabot tumani",
    },
    {
        id: "132",
        region_id: "9",
        value: "Oltinsoy tumani",
        label: "Oltinsoy tumani",
    },
    {
        id: "133",
        region_id: "9",
        value: "Sariosiyo tumani",
        label: "Sariosiyo tumani",
    },
    { id: "134", region_id: "9", value: "Termiz tumani", label: "Termiz tumani" },
    { id: "135", region_id: "9", value: "Termiz shahri", label: "Termiz shahri" },
    { id: "136", region_id: "9", value: "Uzun tumani", label: "Uzun tumani" },
    { id: "137", region_id: "9", value: "Sherobod tumani", label: "Sherobod tumani" },
    { id: "138", region_id: "9", value: "Shorchi tumani", label: "Shorchi tumani" },
    { id: "139", region_id: "10", value: "Boyovut tumani", label: "Boyovut tumani" },
    {
        id: "140",
        region_id: "10",
        value: "Guliston tumani",
        label: "Guliston tumani",
    },
    { id: "141", region_id: "10", value: "Guliston shahri", label: "Guliston shahri" },
    {
        id: "142",
        region_id: "10",
        value: "Mirzaobod tumani",
        label: "Mirzaobod tumani",
    },
    { id: "143", region_id: "10", value: "Oqoltin tumani", label: "Oqoltin tumani" },
    {
        id: "144",
        region_id: "10",
        value: "Sayxunobod tumani",
        label: "Sayxunobod tumani",
    },
    { id: "145", region_id: "10", value: "Sardoba tumani", label: "Sardoba tumani" },
    {
        id: "146",
        region_id: "10",
        value: "Sirdaryo tumani",
        label: "Sirdaryo tumani",
    },
    { id: "147", region_id: "10", value: "Xavos tumani", label: "Xavos tumani" },
    { id: "148", region_id: "10", value: "Shirin shahri", label: "Shirin shahri" },
    { id: "149", region_id: "10", value: "Yangiyer shahri", label: "Yangiyer shahri" },
    { id: "150", region_id: "11", value: "Angiren shahri", label: "Angiren shahri" },
    { id: "151", region_id: "11", value: "Bekabod tumani", label: "Bekabod tumani" },
    { id: "152", region_id: "11", value: "Bekabod shahri", label: "Bekabod shahri" },
    { id: "153", region_id: "11", value: "Boka tumani", label: "Boka tumani" },
    {
        id: "154",
        region_id: "11",
        value: "Bostonliq tumani",
        label: "Bostonliq tumani",
    },
    {
        id: "155",
        region_id: "11",
        value: "Zangiota tumani",
        label: "Zangiota tumani",
    },
    { id: "156", region_id: "11", value: "Qibray tumani", label: "Qibray tumani" },
    {
        id: "157",
        region_id: "11",
        value: "Quyichirchiq tumani",
        label: "Quyichirchiq tumani",
    },
    {
        id: "158",
        region_id: "11",
        value: "Oqqorgon tumani",
        label: "Oqqorgon tumani",
    },
    { id: "159", region_id: "11", value: "Olmaliq shahri", label: "Olmaliq shahri" },
    {
        id: "160",
        region_id: "11",
        value: "Ohangaron tumani",
        label: "Ohangaron tumani",
    },
    { id: "161", region_id: "11", value: "Parkent tumani", label: "Parkent tumani" },
    { id: "162", region_id: "11", value: "Piskent tumani", label: "Piskent tumani" },
    {
        id: "163",
        region_id: "11",
        value: "Ortachirchiq tumani",
        label: "Ortachirchiq tumani",
    },
    { id: "164", region_id: "11", value: "Chinoz tumani", label: "Chinoz tumani" },
    { id: "165", region_id: "11", value: "Chirchiq shahri", label: "Chirchiq shahri" },
    {
        id: "166",
        region_id: "11",
        value: "Yuqorichirchiq tumani",
        label: "Yuqorichirchiq tumani",
    },
    { id: "167", region_id: "11", value: "Yangiyol tumani", label: "Yangiyol tumani" },
    { id: "168", region_id: "12", value: "Beshariq tumani", label: "Beshariq tumani" },
    { id: "169", region_id: "12", value: "Bogdod tumani", label: "Bogdod tumani" },
    { id: "170", region_id: "12", value: "Buvayda tumani", label: "Buvayda tumani" },
    {
        id: "171",
        region_id: "12",
        value: "Dangara tumani",
        label: "Dangara tumani",
    },
    { id: "172", region_id: "12", value: "Yozyovon tumani", label: "Yozyovon tumani" },
    { id: "173", region_id: "12", value: "Quva tumani", label: "Quva tumani" },
    { id: "174", region_id: "12", value: "Quvasoy shahri", label: "Quvasoy shahri" },
    { id: "175", region_id: "12", value: "Qoqon shahri", label: "Qoqon shahri" },
    {
        id: "176",
        region_id: "12",
        value: "Qoshtepa tumani",
        label: "Qoshtepa tumani",
    },
    { id: "177", region_id: "12", value: "Margilon shahri", label: "Margilon shahri" },
    {
        id: "178",
        region_id: "12",
        value: "Oltiariq tumani",
        label: "Oltiariq tumani",
    },
    { id: "179", region_id: "12", value: "Rishton tumani", label: "Rishton tumani" },
    { id: "180", region_id: "12", value: "Sox tumani", label: "Sox tumani" },
    { id: "181", region_id: "12", value: "Toshloq tumani", label: "Toshloq tumani" },
    {
        id: "182",
        region_id: "12",
        value: "Uchkoprik tumani",
        label: "Uchkoprik tumani",
    },
    {
        id: "183",
        region_id: "12",
        value: "Ozbekiston tumani",
        label: "Ozbekiston tumani",
    },
    { id: "184", region_id: "12", value: "Fargona tumani", label: "Fargona tumani" },
    { id: "185", region_id: "12", value: "Fargona shahri", label: "Fargona shahri" },
    { id: "186", region_id: "12", value: "Furqat tumani", label: "Furqat tumani" },
    { id: "187", region_id: "13", value: "Bogot tumani", label: "Bogot tumani" },
    { id: "188", region_id: "13", value: "Gurlan tumani", label: "Gurlan tumani" },
    {
        id: "189",
        region_id: "13",
        value: "Qoshkopir tumani",
        label: "Qoshkopir tumani",
    },
    { id: "190", region_id: "13", value: "Urganch tumani", label: "Urganch tumani" },
    { id: "191", region_id: "13", value: "Urganch shahri", label: "Urganch shahri" },
    { id: "192", region_id: "13", value: "Xiva tumani", label: "Xiva tumani" },
    {
        id: "193",
        region_id: "13",
        value: "Xazarasp tumani",
        label: "Xazarasp tumani",
    },
    { id: "194", region_id: "13", value: "Xonqa tumani", label: "Xonqa tumani" },
    { id: "195", region_id: "13", value: "Shavot tumani", label: "Shavot tumani" },
    {
        id: "196",
        region_id: "13",
        value: "Yangiariq tumani",
        label: "Yangiariq tumani",
    },
    {
        id: "197",
        region_id: "13",
        value: "Yangibozor tumani",
        label: "Yangibozor tumani",
    },
    {
        id: "198",
        region_id: "14",
        value: "Bektimer tumani",
        label: "Bektimer tumani",
    },
    {
        id: "199",
        region_id: "14",
        value: "Mirzo Ulug'bek tumani",
        label: "Mirzo Ulug'bek tumani",
    },
    { id: "200", region_id: "14", value: "Mirobod tumani", label: "Mirobod tumani" },
    { id: "201", region_id: "14", value: "Olmazor tumani", label: "Olmazor tumani" },
    {
        id: "202",
        region_id: "14",
        value: "Sirg'ali tumani",
        label: "Sirg'ali tumani",
    },
    { id: "203", region_id: "14", value: "Uchtepa tumani", label: "Uchtepa tumani" },
    {
        id: "204",
        region_id: "14",
        value: "Yashnobod tumani",
        label: "Yashnobod tumani",
    },
    {
        id: "205",
        region_id: "14",
        value: "Chilonzor tumani",
        label: "Chilonzor tumani",
    },
    {
        id: "206",
        region_id: "14",
        value: "Shayxontohur tumani",
        label: "Shayxontohur tumani",
    },
    {
        id: "207",
        region_id: "14",
        value: "Yunusobod tumani",
        label: "Yunusobod tumani",
    },
    {
        id: "208",
        region_id: "14",
        value: "Yakkasaroy tumani",
        label: "Yakkasaroy tumani",
    },
    {
        id: "209",
        region_id: "1",
        value: "Taxiatosh shahri",
        label: "Taxiatosh shahri",
    },
    { id: "210", region_id: "2", value: "Asaka shahri", label: "Asaka shahri" },
    {
        id: "211",
        region_id: "9",
        value: "Bandixon tumani",
        label: "Bandixon tumani",
    },
    {
        id: "212",
        region_id: "11",
        value: "Ohangaron shahri",
        label: "Ohangaron shahri",
    },
    { id: "213", region_id: "11", value: "Yangiyol shahri", label: "Yangiyol shahri" },
    { id: "215", region_id: "11", value: "Toshkent tumani", label: "Toshkent tumani" },
    { id: "216", region_id: "13", value: "Xiva shahri", label: "Xiva shahri" },
    {
        id: "217",
        region_id: "13",
        value: "Do'stlik shahri",
        label: "Do'stlik shahri",
    },
    {
        id: "218",
        region_id: "14",
        value: "Yangihayot tumani",
        label: "Yangihayot tumani",
    },
    {
        id: "219",
        region_id: "13",
        value: "Tuproqqala tumani",
        label: "Tuproqqala tumani",
    },
    {
        id: "220",
        region_id: "7",
        value: "Davlatobod tumani",
        label: "Davlatobod tumani",
    },
    { id: "221", region_id: "6", value: "Gozgon shahri", label: "Gozgon shahri" },
    { id: "222", region_id: "1", value: "Bozatov tumani", label: "Bozatov tumani" },
    { id: "224", region_id: "5", value: "Shahrisabz shahri", label: "Shahrisabz shahri" },
    { id: "225", region_id: "5", value: "Kokdala tumani", label: "Kokdala tumani" },
]
